services:
  - type: web
    name: payment-approval-app
    env: node
    buildCommand: |
      npm install
      npm run build
      mkdir -p /opt/render/project/src/dist
      cp -r dist/* /opt/render/project/src/dist/
    startCommand: node server.js
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
