services:
  - type: web
    name: payment-approval-app
    env: node
    buildCommand: |
      npm install
      npm run build
      pwd
      echo "Build directory contents:"
      ls -la dist/
    startCommand: node server.js
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    disk:
      name: build-disk
      mountPath: /opt/render/project/src/dist
      sizeGB: 1
